# Generated by Django 4.2.24 on 2025-09-22 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('fono1', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fono2', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='especies/')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra'), ('I', 'Indeterminado')], max_length=1)),
                ('edad', models.PositiveIntegerField(help_text='Años (aprox.)')),
                ('n_chip', models.CharField(blank=True, max_length=30, verbose_name='N° de chip')),
                ('raza', models.CharField(blank=True, max_length=60)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mascotas', to='core.dueno')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mascotas', to='core.especie')),
            ],
        ),
    ]
